# Numpy


In [31]:
import numpy as np
a = np.array([1,2,3])
b = np.array([1,5,15,435,77], dtype="int16")
c = np.array([[19,9,21,54],[6,6,543,7]], dtype="int32")
print(a)
print(b)
print(c)

[1 2 3]
[  1   5  15 435  77]
[[  19    9   21   54]
 [   6    6  543    7]
 [ 214   45 6345 4523]]


In [9]:
#get dimesion
a.ndim

1

In [13]:
c.shape


(2, 4)

In [23]:
b.dtype

dtype('int16')

In [70]:
b.itemsize

5

In [24]:
c.size

8

In [29]:
#total size
a.nbytes


12

In [62]:
e = np.array([[[19,9,21,54],[6,6,543,7],[214,45,6345,4523]],[[179,23,654,564],[61,76,53,7],[21,455,635,453]]])
d = np.array([[19,9,21,54],[6,6,543,7],[214,45,6345,4523]])


In [72]:
d[:,3]
d[1,1:]


array([  6, 543,   7])

In [55]:
e.shape

(2, 3, 4)

In [85]:
e[0,1,3]
e[1,2,-2:-1]
#e[1,2,1:-1]

array([635])

In [ ]:
e[0,1,3] = 60
print()