# Numpy


In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,5,15,435,77], dtype="int16")
c = np.array([[19,9,21,54],[6,6,543,7]], dtype="int32")
print(a)
print(b)
print(c)

[1 2 3]
[  1   5  15 435  77]
[[ 19   9  21  54]
 [  6   6 543   7]]


In [9]:
#get dimesion
a.ndim

1

In [13]:
c.shape


(2, 4)

In [23]:
b.dtype

dtype('int16')

In [70]:
b.itemsize

5

In [24]:
c.size

8

In [29]:
#total size
a.nbytes


12

In [3]:
e = np.array([[[19,9,21,54],[6,6,543,7],[214,45,6345,4523]],[[179,23,654,564],[61,76,53,7],[21,455,635,453]]])
d = np.array([[19,9,21,54],[6,6,543,7],[214,45,6345,4523]])


In [12]:
# getting a specific column

d[:,3]
# d[1,1:]


array([  54,    7, 4523])

In [15]:
e.shape


(2, 3, 4)

In [85]:
e[0,1,3]
e[1,2,-2:-1]
#e[1,2,1:-1]

array([635])

In [23]:
# getting a specific row

e[0]



array([[  19,    9,   21,   54],
       [   6,    6,  543,    7],
       [ 214,   45, 6345, 4523]])

In [19]:
# getting a specific element
e[0,1,1]


6

In [26]:
# getting a little more fancy

e[0,1:-2:2]

array([], shape=(0, 4), dtype=int32)

In [6]:
e[0,1,1] = 5
e[0,1,1]


5

In [7]:
d.shape


(3, 4)

In [12]:
d.ndim

2

In [14]:
e.ndim

3

# initializing Different Types of Arrays


In [16]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other num
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number(full_like)
np.full_like(e, 4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [4]:
# imitialize decimal numbers
np.random.rand(4,2, 3)
# 4 ROWS IN  A 2 DIMENSION AND 3 NUMBERS/ COLUMN


array([[[0.74803102, 0.45721777, 0.53709281],
        [0.17023517, 0.94521869, 0.35938118]],

       [[0.52476003, 0.9751407 , 0.76006135],
        [0.84216258, 0.34992533, 0.9873389 ]],

       [[0.21657067, 0.22480973, 0.55526033],
        [0.20044454, 0.23023355, 0.62173352]],

       [[0.16536947, 0.47676238, 0.68141119],
        [0.45393852, 0.24128831, 0.24862817]]])

In [7]:
np.random.random_sample(a.shape)

array([0.58493316, 0.81637868, 0.44266037])

In [20]:
# random Integer values
np.random.randint(-6,7, size=(3,2,4))

array([[[-1, -6,  6,  3],
        [-5,  5, -2, -2]],

       [[-3,  0, -6,  4],
        [ 6, -4, -6,  2]],

       [[-3,  0,  4,  0],
        [ 6,  4, -1,  6]]])

In [21]:
# THE IDENTITY MATRIX
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
# repeat an array

arr = np.array([[2,4,5]])
r1=np.repeat(arr, 3,axis=0)
print(r1)

[[2 4 5]
 [2 4 5]
 [2 4 5]]


In [29]:
output = np.ones((5,5))
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
z = np.zeros((3,3))
z[1,1] = 9
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [36]:
a= np.array([1,2,3])
b = a.copy()
b[0] = 100
b


array([100,   2,   3])

In [37]:
print(a)

[1 2 3]


### Mathematics


In [49]:
a + 4


array([15, 16, 17])

In [41]:
a - 2 

array([-1,  0,  1])

In [43]:
a * 2

array([2, 4, 6])

In [44]:
a / 2

array([0.5, 1. , 1.5])

In [50]:
a ** 2

array([121, 144, 169], dtype=int32)

In [51]:
# Take the sign
np.sin(e)

array([[[ 0.14987721,  0.41211849,  0.83665564, -0.55878905],
        [-0.2794155 , -0.2794155 ,  0.47549715,  0.6569866 ],
        [ 0.36319945,  0.85090352, -0.85061836, -0.77922052]],

       [[ 0.07072217, -0.8462204 ,  0.52160244, -0.99646411],
        [-0.96611777,  0.56610764,  0.39592515,  0.6569866 ],
        [ 0.83665564,  0.50633965,  0.38783721,  0.57340657]]])

In [52]:
np.cos(d)

array([[ 0.98870462, -0.91113026, -0.54772926, -0.82930983],
       [ 0.96017029,  0.96017029, -0.87971726,  0.75390225],
       [ 0.93171141,  0.52532199,  0.52578361,  0.62674985]])

### LINEAR ALGEBRA

In [88]:
a = np.ones((2,3))
print(a)


[[1. 1. 1.]
 [1. 1. 1.]]


In [81]:
b= np.full((3,2), 2)
b


array([[2, 2],
       [2, 2],
       [2, 2]])

In [89]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [90]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics


In [91]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
# the minimum number
np.min(stats, axis=1)

array([1, 4])

In [96]:
# the  maximum number
np.max(stats, axis=1)

array([3, 6])

# Reorganizing arrays


In [111]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,1,4))
after

[[1 2 3 4]
 [5 6 7 8]]


array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [113]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2= np.array([5,6,7,8])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
# horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])