# Numpy


In [1]:
import numpy as np

a = np.array([1,2,3])
b = np.array([1,5,15,435,77], dtype="int16")
c = np.array([[19,9,21,54],[6,6,543,7]], dtype="int32")
print(a)
print(b)
print(c)

[1 2 3]
[  1   5  15 435  77]
[[ 19   9  21  54]
 [  6   6 543   7]]


In [9]:
#get dimesion
a.ndim

1

In [13]:
c.shape


(2, 4)

In [23]:
b.dtype

dtype('int16')

In [70]:
b.itemsize

5

In [24]:
c.size

8

In [29]:
#total size
a.nbytes


12

In [3]:
e = np.array([[[19,9,21,54],[6,6,543,7],[214,45,6345,4523]],[[179,23,654,564],[61,76,53,7],[21,455,635,453]]])
d = np.array([[19,9,21,54],[6,6,543,7],[214,45,6345,4523]])


In [12]:
# getting a specific column

d[:,3]
# d[1,1:]


array([  54,    7, 4523])

In [15]:
e.shape


(2, 3, 4)

In [85]:
e[0,1,3]
e[1,2,-2:-1]
#e[1,2,1:-1]

array([635])

In [23]:
# getting a specific row

e[0]



array([[  19,    9,   21,   54],
       [   6,    6,  543,    7],
       [ 214,   45, 6345, 4523]])

In [19]:
# getting a specific element
e[0,1,1]


6

In [26]:
# getting a little more fancy

e[0,1:-2:2]

array([], shape=(0, 4), dtype=int32)

In [6]:
e[0,1,1] = 5
e[0,1,1]


5

In [7]:
d.shape


(3, 4)

In [12]:
d.ndim

2

In [14]:
e.ndim

3

# initializing Different Types of Arrays


In [16]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
# all 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [22]:
# Any other num
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
# Any other number(full_like)
np.full_like(e, 4)

array([[[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]]])

In [30]:
# imitialize decimal numbers
np.random.rand(4,2, 3)
# 4 ROWS IN  A 2 DIMENSION AND 3 NUMBERS/ COLUMN


array([[[0.64826033, 0.34240816, 0.74983568],
        [0.43805422, 0.41416604, 0.03496098]],

       [[0.90460028, 0.88659356, 0.70181094],
        [0.77467987, 0.91367583, 0.8537439 ]],

       [[0.30395331, 0.33276749, 0.38918679],
        [0.62688404, 0.11872082, 0.57868808]],

       [[0.60398829, 0.12783555, 0.85077614],
        [0.88654335, 0.44165008, 0.62522518]]])